''' FUTURE PLAN: SEPARATE APP INTO DIFFERENT MODULES AND IMPORT THEM TO MAKE EACH FUNCTION MORE EASILY CORRECTED
IMPLEMENT SQL DATABASES POSSIBLY INSTEAD OF CSV FILES
POSSIBLY USE LIBRARIES LIKE PANDAS TO EXPERIMENT
'''
print('new line')